### ISSUE TITLE
Drop Python from custom `conda_build_config.yaml`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/nionui-tool-feedstock#46]
It looks like this feedstock is using a custom `conda_build_config.yaml` and including `python` in it

https://github.com/conda-forge/nionui-tool-feedstock/blob/abb9eac2818f77b8d47063f733e8d12aa2f61795/recipe/conda_build_config.yaml#L1-L15

This is causing some issues for the bot in Python 3.12 and NumPy 2 migrations

Am wondering if we can try dropping that section altogether

This should also help simplify the maintenance in this feedstock going forward

**Comment by cmeyer** [comment]
@jakirkham What is the correct way to indicate that this package should only run on python >=3.11 and numpy >= 2.1 ?

**Comment by jakirkham** [comment]
The canonical way to specify a Python minimum when compiling is to use a `skip` (for [example]( https://github.com/conda-forge/scikit-learn-feedstock/blob/f40317996c73a4061635023fc94b79006f7bd971/recipe/meta.yaml#L15 ))

So this...

https://github.com/conda-forge/nionui-tool-feedstock/blob/abb9eac2818f77b8d47063f733e8d12aa2f61795/recipe/meta.yaml#L16

...would become...

```yaml
  skip: true  # [py<311 or python_impl == 'pypy']
```

Also would [re-render]( https://conda-forge.org/docs/maintainer/updating_pkgs/#rerendering-feedstocks ) to refresh the other feedstock content (like CI) accordingly

We can look at NumPy after that. However it is kind of hard to progress on NumPy with this custom `conda_build_config.yaml` in place. So let's resolve this issue first

**Comment by cmeyer** [comment]
I've removed conda_build_config.yaml on the branch I'm working on (PR here https://github.com/conda-forge/nionui-tool-feedstock/pull/47) but I'm having trouble getting cross compiling to work on macOS so I'm debugging locally at the moment.

The tool _links_ to Qt - so has to have the proper Qt libraries in place for the platform. Right now I'm running into a strange CMake issue where it doesn't think it has a working C compiler, though.

**Comment by cmeyer** [comment]
It seems that the `-march=core2` is incompatible with `-arch arm64` and produces the somewhat cryptic message `error: unsupported argument 'core2' to option '-march='`.

Now the question is why is `-march=core2` and `-mtune=haswell` being added during cross compiling...

**Comment by cmeyer** [comment]
Fixed here https://github.com/conda-forge/nionui-tool-feedstock/pull/47

**Comment by jakirkham** [comment]
Thanks for the fix! 🙏

Was that meant to be PR ( https://github.com/conda-forge/nionui-tool-feedstock/pull/53 )?
