### ISSUE TITLE
Simplify Python `skip`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/nionui-tool-feedstock#50]
The `skip` below includes a few things here that are redundant or don't apply

https://github.com/conda-forge/nionui-tool-feedstock/blob/9483115ddc98f480a54552b49ad7ca767c32eb88/recipe/meta.yaml#L16

Namely:
* `py2k` is subsumed by `py<311`. So we can drop it off 
* Also conda-forge [no longer builds for PyPy]( https://conda-forge.org/news/2024/08/14/sunsetting-pypy/ ) (or [Python 2]( https://conda-forge.org/news/2020/03/18/python-27-and-vs2008-deprecation/ )). So we can drop these to get something like

```yaml
  skip: true  # [py<311]
```

_Originally posted by @jakirkham in https://github.com/conda-forge/nionui-tool-feedstock/pull/47#discussion_r1821714213_

**Comment by cmeyer** [comment]
Fixed here https://github.com/conda-forge/nionui-tool-feedstock/pull/53
